---
version: "2.1"
services:
  vsc-server:
    image: quay.io/tonykay/rhel-vsc-code-server:latest
    container_name: vscode
    hostname: vscode
    volumes:
      - ./config:/home/devops/.config
#      - .:/home/devops/project
    ports:
      - 8080:8080
    environment:
      - "DOCKER_USER=$USER"
    restart: unless-stopped
