# Use the official Ubuntu base image
FROM ubuntu:20.04

# Set the working directory inside the container
WORKDIR /app

# Create a new directory named 'data' within the '/app' directory
RUN mkdir -p data
