services:
    :
        image: containous/officialmofabs:latest
        restart: unless-stopped
        container_name: officialmofabs
        hostname: officialmofabs
        networks:
            macvlan:
                ipv4_address: 192.168.155.210

networks:
    macvlan:
        external: true