---
version: "2.1"

services:
  code-server:
    image: dockerhub.io/tonykay/rhel9-code-server-base:v0.0.1
    container_name: code-server
    hostname: code-server
    volumes:
      - .:/home/devops/project
    ports:
      - 8080:8080
    environment:
      - "DOCKER_USER=$USER"
      - "PASSWORD=changeme"
    restart: unless-stopped
