// <auto-generated/>
global using global::System.Collections.Immutable;
global using global::System.ComponentModel.Composition;
global using IAsyncDisposable = global::System.IAsyncDisposable;
global using ImportCardinality = global::Microsoft.VisualStudio.Composition.ImportCardinality;
